[build]
  publish = "."

[functions]
  included_files = ["default/**", "protected/**"]

[[redirects]]
  from = "/api/out"
  to = "/.netlify/functions/out"
  status = 200
  force = true

[[redirects]]
  from = "/api/word"
  to = "/.netlify/functions/word"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true